config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# app > models > user
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data[:email]).first

    user ||= User.create(name: data[:name], email: data[:email], password: Devise.friendly_token[0, 20])

    user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal

# app > controllers > application_controller
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
# frozen_stribg_literal: true

# app > controllers > events_controller
class EventsController < ApplicationController
  def index
    result = GoogleCalendarWrapper.new(current_user).current_users_events(params[:format])
    handle_authentication_error(result)
    if result.is_a?(String)
      flash.now[:alert] = "Please try again. There seems to be a #{result} error."
    else
      @page_token = result.to_h[:next_page_token]
      @events = result.to_h[:items]
      @events.uniq! { |event| event[:summary] }
    end
  end

  def show
    selected_event = GoogleCalendarWrapper.new(current_user).show_event(params[:id])
    handle_authentication_error(selected_event)
    if selected_event.is_a?(String)
      redirect_to events_path
      flash.now[:alert] = "Please try again. There seems to be a #{selected_event} error."
    else
      @event = selected_event.to_h
    end
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    options = {
      "location": 'Tntra Vadodara',
      "remainders": {
        "email": '20',
        "popup": '10'
      },
      "guests_can_modify": false,
      "guests_can_invite_others": false,
      "guests_can_see_other_guests": false,
      "recurrence": [
        'RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1'
      ],
      "visibility": 'default',
      "send_updates": "all",
      "send_notifications": true,
      "conference_data": {
        "create_request": {
          "conference_solution_key": {
            "type": "hangoutsMeet"
          },
          "request_id": SecureRandom.alphanumeric
        }
      }
    }
    event = { summary: event_params[:title],
              description: event_params[:description],
              start_date: event_start_date,
              end_date: event_end_date,
              attendees: event_params[:members].split(',').map(&:strip) }
    response = GoogleCalendarWrapper.new(current_user).create_calendar_event(event, options)
    handle_authentication_error(response)
    respond_to do |format|
      if response.instance_of?(::Google::Apis::CalendarV3::Event)
        format.html { redirect_to event_url(response.to_h[:id]), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      elsif response == '"Pass Event Properly"'
        format.html do
          render :new, status: :unprocessable_entity 
          flash.now[:alert] = 'Please pass necessary details for creating an event'
        end
      else
        format.html do
          render :new, status: :unprocessable_entity 
          flash.now[:alert] = "Please try again. There seems to be a #{result} error."
        end
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    response = GoogleCalendarWrapper.new(current_user).cancel_event(params[:id])
    handle_authentication_error(response)
    if response == ''
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html do
          redirect_to events_url, status: :unprocessable_entity
          flash.now[:alert] = "Please try again. There seems to be a #{result} error."
        end
        return
      end
    end
  end

  private

  def event_params
    params.fetch(:event, {})
  end

  def event_start_date
    Time.new(event_params['start_date(1i)'].to_i, event_params['start_date(2i)'].to_i,
             event_params['start_date(3i)'].to_i, event_params['start_date(4i)'].to_i,
             event_params['start_date(5i)'].to_i, '00'.to_i, '+05:30')
  end

  def event_end_date
    Time.new(event_params['end_date(1i)'].to_i, event_params['end_date(2i)'].to_i,
             event_params['end_date(3i)'].to_i, event_params['end_date(4i)'].to_i,
             event_params['end_date(5i)'].to_i, '00'.to_i, '+05:30')
  end

  def handle_authentication_error(result)
    return unless result == 'Unauthorized'

    sign_out(current_user)
    authenticate_user!
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      auth = request.env['omniauth.auth']
      @user.access_token = auth.credentials.token
      @user.expires_at = auth.credentials.expire_at
      @user.refresh_token = auth.credentials.refresh_token
      @user.save!
      sign_in(@user)
      redirect_to root_path
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div><br>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div><br>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div><br>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div><br>

  <div class="field">
    <%= form.label :members %>
    <%= form.text_field :members %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="events">
  <table>
    <% if @events.nil? %>
      <p> No Data Fetched </p>
    <% else %>
      <tr>
        <th>Title</th>
        <th>Creator</th>
        <th>At</th>
        <th>Actions</th>
      </tr>
    <% end %>
    <% @events = [] if @events.nil? %>
    <% @events.each do |event| %>
      <tr>
        <td><%= event[:summary] %></td>
        <td><%= event[:creator][:email] %></td>
        <td><%= event[:start][:date_time].strftime("%d-%m-%Y at %I:%M%p") %></td>
        <td><%= link_to 'View', event_path(event[:id]) %></td>
        <td><%= link_to "Delete", event_path(event[:id]), data: {
          turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %> </td>
      </tr>
    <% end %>
      
  </table>
</div>

<% unless @page_token.nil? %>
  <%= link_to 'Next', events_path(@page_token) %>
<% end %>
<% unless !@page_token.nil? %>
  <%= link_to 'Back', events_path %>
<% end %>
<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<h3><%= @event[:summary] %></h3><br><br>

<p><b>Description:</b> <%= @event[:description] %> </p><br>

<p><b>Created By:</b> <%= @event[:creator][:email] %> </p>

<b>Attendees:</b>
<table>
  <tr>
    <th>Email</th>
    <th>Response</th>
  </tr>
  <% if @event[:attendees].present? %> 
    <% @event[:attendees].each do |attendee| %>
      <tr>
        <td><%= attendee[:email] %></td>
        <td><%= attendee[:response_status].underscore.split('_').join(' ').capitalize %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<div>
  <%= link_to "Back to events", events_path %> | <%= link_to "Delete this event", event_path(@event[:id]), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="alert" style="color: red"><%= alert %></p>
    <% if current_user.present? %>
      <%= button_to( "Log Out", destroy_user_session_path, method: :delete ) %>
    <% end %>
    <%= yield %>
  </body>
</html>